### PR TITLE
refactor: change CookieSameSite to be an enum

### PR DESCRIPTION
**Pull request by keithamus**
This changes the `CookieSameSite` type to be an `enum`, which allows us to be more consistent when using the SameSite value across the codebase.

/cc @markcellus @koddsson

### CODE REVIEW

**Review by koddsson — APPROVED** [review]
Makes sense 👍🏻

**Review by markcellus — APPROVED** [review]
lgtm

**Comment by koddsson** [comment]
Maybe we should remove Travis at this point since it's a lot slower than GitHub Actions 🤔 

image

**Comment by markcellus** [comment]
Yeah I noticed that. should be fine to just remove it right?

**Pull request merged**
