### PR TITLE
Remove `next` commits from master to unblock us from releasing fixes to 3.0

### PR DESCRIPTION
**Pull request by markcellus**
We've made some small fixes in master that we should release with a new version. 

However, there are refactor commits on master that we don't want to be released. So this removes those commits from the master branch. But no worries--these commits are still on the [`next` branch](https://github.com/markcellus/cookie-store/tree/next). :rocket: 

After this PR is merged, I will create another release that contains the small fixes left on master.

### CODE REVIEW

**Comment by keithamus** [comment]
62ea080f031dc8863299d59cd954f05d9f01bf46, e9eff9aa5fc724e65ba1eaea7e15f658d537e808, c070227229a6ebc671dbe719f1ecf8a3a2254c0e, all need to be reverted too I believe.

**Comment by markcellus** [comment]
@keithamus Ah yes. I looked at those but those seemed to be more like "fixes" or "small features" that could go into a minor version bump, max. Do you think those would warrant a major version bump if we keep them? :thinking:

**Comment by keithamus** [comment]
They feel like a major bump, for example 62ea080 introduces throwing `TypeError`s.

**Comment by markcellus** [comment]
Yeah looking a little closer, having the `CookieStore` extend `EventTarget` may cause some backwards-compat issues too.

**Comment by markcellus** [comment]
I ended up just reverting master back to v3.0.0 tag, so closing.

**Pull request closed without merging**
